// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function EvaluateInput(arg1:Array<string>):Promise<Array<boolean>>;

export function LoadDotDfa():Promise<string>;

export function LoadDotIn():Promise<Array<string>>;
