// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function EvaluateInput(arg1) {
  return window['go']['main']['App']['EvaluateInput'](arg1);
}

export function LoadDotDfa() {
  return window['go']['main']['App']['LoadDotDfa']();
}

export function LoadDotIn() {
  return window['go']['main']['App']['LoadDotIn']();
}
