// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function EvaluateInput(arg1:Array<string>):Promise<Array<boolean>>;

export function LoadDotDfa():Promise<main.DfaLoadResult>;

export function LoadDotIn():Promise<main.InLoadResult>;

export function SaveOutput(arg1:Array<boolean>):Promise<void>;
